### ISSUE TITLE
How do you achieve a cap on transfer fees ? it's impossible 😨😨😨

### ISSUE THREAD

**Issue by ilovedesert001** [fuseio/fuse-network#106]
https://studio.fuse.io/view/price
Fees may rise in the future but are capped at $0.01 per transaction 

0.01$
Transaction Cost

What if the fuse price rises to 100 $ or even 1000 $  ?

**Comment by Marksmargon** [comment]
Hi! thanks for the feedback but you are acutally right and we have been updating our fee model recentrly - this page was built long time ago and will soon be updated
You can read more about it here: https://medium.com/fusenet/fuses-half-year-update-the-road-to-scale-and-decentralization-bc59d6cb22f7?source=collection_home---4------6-----------------------

**Comment by ilovedesert001** [comment]
> Hi! thanks for the feedback but you are acutally right and we have been updating our fee model recentrly - this page was built long time ago and will soon be updated
> You can read more about it here: https://medium.com/fusenet/fuses-half-year-update-the-road-to-scale-and-decentralization-bc59d6cb22f7?source=collection_home---4------6-----------------------

Thanks.
