### ISSUE TITLE
Is Nethermind a new node client?

### ISSUE THREAD

**Issue by YuXiaoCoder** [fuseio/fuse-network#138]
https://github.com/fuseio/nethermind

**Comment by 0xnagu** [comment]
@YuXiaoCoder Yes. Fuse will be migrating to Nethermind client software. Fuse nodes are currently run using OpenEthereum client software. With the deprecation of OE, we are actively looking for a new client.

Fuse spark testnet is mostly migrated to Nethermind.

Fuse mainnet will be gradually migrated to Nethermind. We have been testing and running few Nethermind nodes successfully for a few days now. We want to upgrade the validator nodes and other nodes with more caution and few at a time.

**Comment by YuXiaoCoder** [comment]
When is expected to be planned for mass migration to Nethermind client software?
