### ISSUE TITLE
More compiler versions on fuse explorer please

### ISSUE THREAD

**Issue by CrackerHax** [fuseio/fuse-network#15]
Compiler versions jump from 5.16 to 6.1 while most openzeppelin contracts want 5.5.

In 6+ they changed the format of the pragma statement from ^[version] to >=[version], so they will not compile.

How about at least adding 5.8?

**Comment by LiorRabin** [comment]
Not sure there's an issue here, attached a screenshot where you can see we have all compiler versions including v5.5.

![Screen Shot 2020-01-26 at 9 40 35](https://user-images.githubusercontent.com/6675831/73132180-05e13d80-4020-11ea-8861-e7de501d73e1.png)

**Comment by CrackerHax** [comment]
Strange, here is a screenshot of mine.

![image](https://user-images.githubusercontent.com/6037535/73134610-bc7bf880-3ff5-11ea-85b7-9740ab19f9f7.png)

**Comment by LiorRabin** [comment]
You need to scroll down, v.0.5.16 > v0.5.5
