### ISSUE TITLE
Nethermind script error: bad init of `pass.pwd´

### ISSUE THREAD

**Issue by 0xthedance** [fuseio/fuse-network#159]
Running the [Nethermind script](https://github.com/fuseio/fuse-network/blob/master/nethermind/quickstart.sh) for the first time, fails with the following error:
```
./quickstart.sh: line 584: /root/fuse-validator/fusenet/keystore/pass.pwd: Is a directory
```

A workaround is to first do `touch fusenet/keystore/pass.pwd `

**Comment by gr8h** [comment]
Should be fixed by now
