### ISSUE TITLE
Is the Nethermind supported on mainnet?

### ISSUE THREAD

**Issue by Zheaoli** [fuseio/fuse-network#163]
OE has been archived for a long time, could we use Nethermind to bootstrap the fuse mainnet?

**Comment by Marksmargon** [comment]
Yes, please try and follow this guide:
https://github.com/fuseio/fuse-network/blob/feature/oe-nm-migration/nethermind/OE_Migration.md

**Comment by gr8h** [comment]
Also here's Nethermind guide: https://github.com/fuseio/fuse-network/blob/master/nethermind/README.md

And you can get the snapshot from here: https://storage.googleapis.com/fuse-node-snapshot/nethermind/database.zip
