### ISSUE TITLE
Change the eth speed parameters to average in gas price calculation

### ISSUE THREAD

**Issue by Andrew-Pohl** [fuseio/fuse-network#21]
It is currently observed that the end of cycle contract call on the Eth network is consuming a lot of gas. Could we change the speed parameters for gas price calculations from ethgasstation API from fast to average to help reduce the transaction cost.

**Comment by fileflume** [comment]
Can we do this asap as it's a simple change and wasting money for no benefit.

**Comment by LiorRabin** [comment]
Done

https://github.com/fuseio/fuse-bridge/commit/e775f5b59adaa9c73fddfaf05a8d07b40bb558af
https://github.com/fuseio/fuse-network/commit/fcfbde536bc5c011b96a63617a43b0ed61f8a0ad
https://hub.docker.com/repository/docker/fusenet/native-to-erc20-oracle
