### ISSUE TITLE
quickstart.sh doesn't properly create a new account if the passphrase contains special characters

### ISSUE THREAD

**Issue by shaimo** [fuseio/fuse-network#28]
When creating a new account and using special characters in the passphrase, the generated JSON file is encrypted with a different password than the one that was provided, and therefore cannot be opened later.
I suspect the issue is in these lines:
```
ADDRESS=$(yes $PASSWORD | \
          $PERMISSION_PREFIX docker run \
        --interactive --rm \
        --volume $CONFIG_DIR:/config/custom \
        $DOCKER_IMAGE_PARITY \
        --parity-args account new |\
        grep -o "0x.*")
```
The password is fed to docker/parity through stdin so some of the characters may not pass through as is...

**Comment by Andrew-Pohl** [comment]
I think I may have found the problem here.

The read command on line 205 & 207 needs -r, to treat slashes as text not escape characters.

@shaimo did you're password contain slashes?

Another problem is that the IFS should probably be set to some known value at the top of the script "\n" for example.

**Comment by shaimo** [comment]
@Andrew-Pohl I’m pretty sure it did contain a slash and I think you may be right - good catch!
Obviously needs to be fixed...

**Comment by Andrew-Pohl** [comment]
https://github.com/fuseio/fuse-network/pull/29 

Because I'm bored, I stole @LiorRabin 's job ;)

**Comment by LiorRabin** [comment]
@shaimo can you please verify this after @Andrew-Pohl's fix?
Just pull the latest `quickstart.sh`

**Comment by LiorRabin** [comment]
@shaimo did you check?

**Comment by shaimo** [comment]
@LiorRabin didn't have the chance to touch it since it was reported. I’ll probably need to run a new validator in a couple of weeks so will retest it then...

**Comment by shaimo** [comment]
Checked it today and it worked fine :-)
