### ISSUE TITLE
Consensus smartcontract does not allow commission to be set to 0

### ISSUE THREAD

**Issue by shaimo** [fuseio/fuse-network#30]
Lowest possible value is 1. No reason 0 should not be allowed.

**Comment by fileflume** [comment]
Agree - range should be 0-100. Need to be able to ensure validator node gets 0% tokens.

**Comment by LiorRabin** [comment]
`require (_amount <= 1 * DECIMALS);`
This means that `amount` must be under `1e18`.
For example - 10% fee is `1e17`.

**Comment by Andrew-Pohl** [comment]
> `require (_amount <= 1 * DECIMALS);`
> This means that `amount` must be under `1e18`.
> For example - 10% fee is `1e17`.

I was about to reply this can see any thing in the contract limiting the lower bound

**Comment by shaimo** [comment]
ok, but this is awkward. Why not just allow 0?

**Comment by LiorRabin** [comment]
0 is allowed, there's no limitation to that

**Comment by shaimo** [comment]
I tried a couple of times and my transaction failed

**Comment by shaimo** [comment]
I guess it was somehow a problem with my copy/paste. 0 does seem to work as was also confirmed by Rob.
