### ISSUE TITLE
Gas usage on the executeNewSetSignature increasing with number of validator nodes

### ISSUE THREAD

**Issue by fileflume** [fuseio/fuse-network#32]
From https://github.com/Andrew-Pohl: Gas usage on the executeNewSetSignature call (on mainnet contract) at the end of cycle seems to be increasing each day. My knowledge of contracts are limited (at best) looking at transactions 3months ago we were using roughly 500k gas. 2 weeks ago we were at 1.2million and yesterday 2.4million (doubled in two weeks). I noticed the inputs are increasing in length is this as more validators are coming?. It's currently resulting with the current high eth network load about $11 a day! (this is with the changes to use average gas price) 
example from 2 weeks ago - https://etherscan.io/tx/0xe771fc5b66492f30b19dde8a9c9b78e26a64c3dca8e2174db4f9011650016a5f
example from end of the last cycle - https://etherscan.io/tx/0x9042ec8d95614f61c0eaae250c241c572f3fb958752260d97f0ce3eff6c5bd76

**Comment by LiorRabin** [comment]
https://github.com/fuseio/FIPs/issues/8

**Comment by leonprou** [comment]
@fileflume solved partially by https://github.com/fuseio/FIPs/issues/11, this should end the issue.
closing this for now
