### ISSUE TITLE
Can we increase the Gas limit per block

### ISSUE THREAD

**Issue by Andrew-Pohl** [fuseio/fuse-network#37]
Had some great results from my recent high load tests. One thing I did notice was that the max gas per block of 10mil limits the total number of transactions to a max of 472. Capping the max TPS to ~90. Can we increase this to say 100mil to allow for higher transctions per second. I believe the network can support it and would make for a great marketing claim of 500+ tps.

**Comment by leonprou** [comment]
@Andrew-Pohl Increasing the gas limit will increase the maximum block size, which will increase the load on the validators and make block propagation longer. Eventually you will need more stronger machines for the validators.

There'a s a long discussion about this in bitcoin community: https://en.bitcoin.it/wiki/Block_size_limit_controversy. 

I say when we'll need to TPS, we start increasing the max gas :)

**Comment by Andrew-Pohl** [comment]
> @Andrew-Pohl Increasing the gas limit will increase the maximum block size, which will increase the load on the validators and make block propagation longer. Eventually you will need more stronger machines for the validators.
> 
> There'a s a long discussion about this in bitcoin community: https://en.bitcoin.it/wiki/Block_size_limit_controversy.
> 
> I say when we'll need to TPS, we can start increasing the max gas :)

Sounds good, want to test the network with some big numbers 😉

**Comment by leonprou** [comment]
@Andrew-Pohl closing this now, the discussion can be continued here https://forum.fuse.io/t/fusenet-gas-price-and-gas-limit-per-block/51
