### ISSUE TITLE
End of cycle txs are not going through. ETH_CALL via Infura are spiking on validator nodes.

### ISSUE THREAD

**Issue by fileflume** [fuseio/fuse-network#39]
There are usually 2 end of cycle txs on mainnet. 1 to mine fuse tokens (@~41000/day) and 1 to update the new validator sigs. 

Since the change to a ~48hours cycle time these mainnet txs are either not being created, or only partially so. 

Additionally, validator nodes are seeing a huge spike in eth_calls. I am assuming this is only occurring in the nodes that were chosen to complete the end of cycle txs. 

There appears to be something wrong with the end of cycle process that is causing the txs to fail, and for the node to produce massive amounts of eth_calls to mainnet.

This error has only been seen since the change to 48hour cycle times.
![Screenshot from 2020-06-12 12-39-07](https://user-images.githubusercontent.com/15728425/84499955-8345db80-acab-11ea-9fd0-5f418bf2c93d.png)
![Screenshot from 2020-06-12 12-40-45](https://user-images.githubusercontent.com/15728425/84499958-850f9f00-acab-11ea-9980-b1399ca9d5e0.png)

**Comment by fileflume** [comment]
I've changed the nodes that point to the second account, to use a new account, and re-run quickstart. That will test if this is an infura issue, or a network issue.

**Comment by fileflume** [comment]
Have downloaded the new quickstart, restarted the 2 nodes pointing to a new infura account, and the eth_call is still spiking high. Currently running 8x greater than they should be..

**Comment by fileflume** [comment]
Additionally fuseapp container is resarting frequently, when it never has previously.  2 Errors are being seen. Both attached.
[fuseapp_error.txt](https://github.com/fuseio/fuse-network/files/4776327/fuseapp_error.txt)
[Fuseapp_error2.txt](https://github.com/fuseio/fuse-network/files/4776328/Fuseapp_error2.txt)
The wallets identified in the errors are the wallets from which the error originated. Both errors are calls to the end of cycle contacts.

**Comment by fileflume** [comment]
Haven't found a reason for high eth_call yet.

**Comment by leonprou** [comment]
Sorry for late response,
As you know we did a some fixes till now, 2.0.5 should be more stable.

Closing this for now, but please reopen if there's gonna be more infura spikes. As I learned, Infura spikes are an indication of reoccurring errors in the containers.
