### ISSUE TITLE
Why are we mainnet minting at the end of every cycle anyway?

### ISSUE THREAD

**Issue by CrackerHax** [fuseio/fuse-network#41]
Is there a specific reason why mainnet has to have the same amount of tokens as fusenet? Maybe I have an incomplete picture of how all this is working but seems to me this is a waste of resources in its current form. I mean whats wrong with burning and minting ONLY when tokens are sent over a bridge? 

Example:
Someone sends 10,000 Fuse from fusenet to mainnet
Fusenet burns 10,000 tokens, mainnet mints 10,000 tokens
sender pays fee

Example 2:
Someone sends 10,000 Fuse from mainnet to fusenet
mainnet burns 10,000 tokens, fusenet mints 10,000 tokens
sender pays fee

**Comment by leonprou** [comment]
@CrackerHax we do minting on end of cycle to keep total supply on Ethereum correlated with the total supply on Fuse. 
I hope we'll come back to this after fixing the bridge :)
