### ISSUE TITLE
Parity defaults to a max of 64 connections so bootnodes can't accept new connections

### ISSUE THREAD

**Issue by Andrew-Pohl** [fuseio/fuse-network#51]
I noticed that new nodes either never sync or sit waiting for ages to sync. After a bit of digging I noticed that by default parity nodes only allow a max of 64 connections by default.

 (https://helpmanual.io/help/parity/ see --max-pending-peers)

I will fix this later by upping it 128 should do for now and we will have to restart the boot nodes.

**Comment by Andrew-Pohl** [comment]
One think I have mentioned to Leon on telegram is that parity seems to have a bug where passing it a string as a node key seems to fail at taking a SHA3 256 hash on it. passing in a hex secret key (i.e. performing the hash ourselves works). 

But passing in a string to parity as the node key fails and re generates a new enode address. 

I will make the quickstart script perform the hashing, the only issue here is we will have to update the boot node address and regenerate the docker images since we have no idea what hash was used to generate the enode address previously!

**Comment by Andrew-Pohl** [comment]
https://github.com/fuseio/fuse-network/pull/53

**Comment by leonprou** [comment]
Done by @Andrew-Pohl at #53
