### ISSUE TITLE
Need to get rid of ethgasstation and find another gas estimator solution

### ISSUE THREAD

**Issue by CrackerHax** [fuseio/fuse-network#55]
Eth gas station is limiting queries to 1000 per day which is preventing validators from doing their mainnet work. Need a new solution that does not throttle queries. Probably wouldn't hurt to slow down queries either.

**Comment by Andrew-Pohl** [comment]
Added a configurable gas price oracle here https://github.com/fuseio/fuse-network/pull/65

Currently grabs gas price every 10mins (144 times a day) gasPrice calls are currently free on ethgas station (with key)

**Comment by leonprou** [comment]
so to make this clear, validators are advised to override the `FOREIGN_GAS_PRICE_ORACLE_URL` env var to ethgasstation url with key or the defi-pulse API.
