### ISSUE TITLE
Support EIP712

### ISSUE THREAD

**Issue by leonprou** [fuseio/fuse-network#84]
It become very common EIP now. We should support this
https://eips.ethereum.org/EIPS/eip-712

**Comment by sirpy** [comment]
@leonprou this is already implemented via metamask/web3 there's no specific need to implement eth_signTypedData rpc call

**Comment by leonprou** [comment]
Hey @sirpy,
You are right, put a wrong EIP number here.

Was referring to that one https://eips.ethereum.org/EIPS/eip-1344
